# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  sweetbakeryapp:
    image: sweetbakeryapp
    build:
      context: .
      dockerfile: SweetBakeryApp/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
